/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DataEntryInterface;

import DatabaseManagement.Attribute;
import DatabaseManagement.Attribute.Name;
import DatabaseManagement.AttributeCollection;
import DatabaseManagement.Filters;
import DatabaseManagement.Table;
import General.Controller;
import java.util.ArrayList;
import General.ModificationForm;
import Properties.Mall;
import Properties.Store;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class ModifyPropertyForm extends javax.swing.JFrame implements ModificationForm {

    ArrayList<Store> stores;
    private Controller controller;
    private int currentTab;
    private Store currentStore;
    private Mall currentStoreTabMall;
    private Mall newStoreTabMall;
    private Mall currentMallTabMall;
    String[] floors = new String[]{"G", "F", "S", "H", "O"};

    /**
     * Creates new form CreateNewPropertyForm
     */
    public ModifyPropertyForm() {
        controller = new Controller();
        currentTab = 0;
        initComponents();
        populateFilterMallCMBs();
        hideCurrentFields();
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        DeleteBtn2 = new javax.swing.JButton();
        filterStoreCMB = new javax.swing.JComboBox<>();
        filterFloorCMB = new javax.swing.JComboBox<>();
        filterMallCMB = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        currentStoreNumber = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        newStoreNumber = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        currentSpace = new javax.swing.JTextField();
        newSpace = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        currentMonthly = new javax.swing.JTextField();
        newMonthly = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        currentQuarterly = new javax.swing.JTextField();
        newQuarterly = new javax.swing.JTextField();
        newBiAnnual = new javax.swing.JTextField();
        currentBiAnnual = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        currentAnnual = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        newAnnual = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        currentMallCMB = new javax.swing.JComboBox<>();
        newMallCMB = new javax.swing.JComboBox<>();
        currentFloorCMB = new javax.swing.JComboBox<>();
        newFloorCMB = new javax.swing.JComboBox<>();
        currentStoreName = new javax.swing.JTextField();
        newStoreName = new javax.swing.JTextField();
        currentPurposeCMB = new javax.swing.JComboBox<>();
        newPurposeCMB = new javax.swing.JComboBox<>();
        currentClassCMB = new javax.swing.JComboBox<>();
        newClassCMB = new javax.swing.JComboBox<>();
        ModifyBtn2 = new javax.swing.JButton();
        DeleteBtn1 = new javax.swing.JButton();
        ModifyBtn1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        mallCMB = new javax.swing.JComboBox<>();
        jLabel44 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        currentMallName = new javax.swing.JTextField();
        newMallName = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        newAddress = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        currentAddress = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        deleteMallBtn2 = new javax.swing.JButton();
        modifyMallBtn2 = new javax.swing.JButton();
        deleteMallBtn1 = new javax.swing.JButton();
        modifyMallBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MODIFY/DELETE PROPERTY");
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(102, 102, 102));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFocusable(false);
        jTabbedPane1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jTabbedPane1.setOpaque(true);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(731, 625));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("MODIFY/DELETE STORE");
        jLabel18.setOpaque(true);

        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setHorizontalScrollBar(null);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(613, 600));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setToolTipText("");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setToolTipText("");

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setForeground(new java.awt.Color(0, 102, 0));
        jLabel23.setText("Please fill in this form then submit");

        jLabel26.setBackground(new java.awt.Color(204, 204, 204));
        jLabel26.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Select Mall:");
        jLabel26.setOpaque(true);

        jLabel28.setBackground(new java.awt.Color(204, 204, 204));
        jLabel28.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Select Floor:");
        jLabel28.setOpaque(true);

        jLabel30.setBackground(new java.awt.Color(204, 204, 204));
        jLabel30.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Select Store:");
        jLabel30.setOpaque(true);

        DeleteBtn2.setBackground(new java.awt.Color(255, 0, 0));
        DeleteBtn2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        DeleteBtn2.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBtn2.setText("DELETE");
        DeleteBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtn2ActionPerformed(evt);
            }
        });

        filterStoreCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        filterStoreCMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterStoreCMBActionPerformed(evt);
            }
        });

        filterFloorCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        filterMallCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        filterMallCMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterMallCMBActionPerformed(evt);
            }
        });

        jLabel39.setBackground(new java.awt.Color(204, 204, 204));
        jLabel39.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Mall:");
        jLabel39.setOpaque(true);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Current");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("New");

        jLabel29.setBackground(new java.awt.Color(0, 0, 0));
        jLabel29.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Store Details");
        jLabel29.setOpaque(true);

        jLabel43.setBackground(new java.awt.Color(204, 204, 204));
        jLabel43.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Floor");
        jLabel43.setOpaque(true);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Current");

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("New");

        jLabel47.setBackground(new java.awt.Color(204, 204, 204));
        jLabel47.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Store Name");
        jLabel47.setOpaque(true);

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("New");

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Current");

        jLabel49.setBackground(new java.awt.Color(204, 204, 204));
        jLabel49.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Store Number:");
        jLabel49.setOpaque(true);

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Current");

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 255));
        jLabel15.setText("New");

        jLabel51.setBackground(new java.awt.Color(204, 204, 204));
        jLabel51.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Purpose");
        jLabel51.setOpaque(true);

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 204));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Current");

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 255));
        jLabel17.setText("New");

        jLabel54.setBackground(new java.awt.Color(204, 204, 204));
        jLabel54.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("Class:");
        jLabel54.setOpaque(true);

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 204));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Current");

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 255));
        jLabel20.setText("New");

        jLabel56.setBackground(new java.awt.Color(204, 204, 204));
        jLabel56.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("Space:");
        jLabel56.setOpaque(true);

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 255));
        jLabel21.setText("New");

        jLabel22.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 204));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Current");

        jLabel59.setBackground(new java.awt.Color(204, 204, 204));
        jLabel59.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("Monthly Rate");
        jLabel59.setOpaque(true);

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 204));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Current");

        jLabel31.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 255));
        jLabel31.setText("New");

        jLabel33.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 255));
        jLabel33.setText("New");

        jLabel34.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 0, 204));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Current");

        jLabel64.setBackground(new java.awt.Color(204, 204, 204));
        jLabel64.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("Quarterly Rate:");
        jLabel64.setOpaque(true);

        jLabel37.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 0, 204));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Current");

        jLabel67.setBackground(new java.awt.Color(204, 204, 204));
        jLabel67.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("Bi-Annual Rate");
        jLabel67.setOpaque(true);

        jLabel68.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(0, 0, 255));
        jLabel68.setText("New");

        jLabel69.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 0, 204));
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel69.setText("Current");

        jLabel72.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(0, 0, 255));
        jLabel72.setText("New");

        jLabel73.setBackground(new java.awt.Color(204, 204, 204));
        jLabel73.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel73.setText("Annual Rate:");
        jLabel73.setOpaque(true);

        currentMallCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        newMallCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        newMallCMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMallCMBActionPerformed(evt);
            }
        });

        currentFloorCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        newFloorCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        currentPurposeCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        newPurposeCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        currentClassCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        newClassCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ModifyBtn2.setBackground(new java.awt.Color(0, 0, 255));
        ModifyBtn2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ModifyBtn2.setForeground(new java.awt.Color(255, 255, 255));
        ModifyBtn2.setText("MODIFY");
        ModifyBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyBtn2ActionPerformed(evt);
            }
        });

        DeleteBtn1.setBackground(new java.awt.Color(255, 0, 0));
        DeleteBtn1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        DeleteBtn1.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBtn1.setText("DELETE");
        DeleteBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtn1ActionPerformed(evt);
            }
        });

        ModifyBtn1.setBackground(new java.awt.Color(0, 0, 255));
        ModifyBtn1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ModifyBtn1.setForeground(new java.awt.Color(255, 255, 255));
        ModifyBtn1.setText("MODIFY");
        ModifyBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(filterStoreCMB, 0, 505, Short.MAX_VALUE)
                            .addComponent(filterFloorCMB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(filterMallCMB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(currentFloorCMB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newMallCMB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(currentMallCMB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(currentStoreNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                            .addComponent(newStoreNumber, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentSpace, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                            .addComponent(newSpace, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentMonthly, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                            .addComponent(newMonthly, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentQuarterly, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                            .addComponent(newQuarterly, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newBiAnnual, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentBiAnnual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                            .addComponent(currentAnnual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                            .addComponent(newAnnual, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentPurposeCMB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newPurposeCMB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(currentStoreName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newStoreName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                            .addComponent(currentClassCMB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newClassCMB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newFloorCMB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24)
                            .addComponent(jLabel31)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel37)
                            .addComponent(jLabel68)
                            .addComponent(jLabel69)
                            .addComponent(jLabel72))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(DeleteBtn2)
                .addGap(18, 18, 18)
                .addComponent(ModifyBtn2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DeleteBtn1)
                .addGap(18, 18, 18)
                .addComponent(ModifyBtn1)
                .addGap(238, 238, 238))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(filterMallCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(filterFloorCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(filterStoreCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteBtn1)
                    .addComponent(ModifyBtn1))
                .addGap(34, 34, 34)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(currentMallCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newMallCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel12))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(currentStoreName, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(newStoreName, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(currentStoreNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(newStoreNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)))
                            .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(currentFloorCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newFloorCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(currentPurposeCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newPurposeCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(currentSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(newSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21)))
                            .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(currentMonthly, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(newMonthly, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel31)))
                            .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(currentQuarterly, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(newQuarterly, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33)))
                            .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(currentBiAnnual, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel37))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(newBiAnnual, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel68)))
                            .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(currentAnnual, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel69))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(newAnnual, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel72)))
                            .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(currentClassCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newClassCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteBtn2)
                    .addComponent(ModifyBtn2))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Store", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MODIFY/DELETE MALL");
        jLabel1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("Please fill in this form then submit");

        jLabel42.setBackground(new java.awt.Color(204, 204, 204));
        jLabel42.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Mall:");
        jLabel42.setOpaque(true);

        mallCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        mallCMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mallCMBActionPerformed(evt);
            }
        });

        jLabel44.setBackground(new java.awt.Color(0, 0, 0));
        jLabel44.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Mall Details");
        jLabel44.setOpaque(true);

        jLabel52.setBackground(new java.awt.Color(204, 204, 204));
        jLabel52.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("Mall Name:");
        jLabel52.setOpaque(true);

        jLabel45.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 255));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Current");

        jLabel55.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 0, 255));
        jLabel55.setText("New");

        jLabel61.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 0, 255));
        jLabel61.setText("New");

        jLabel66.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(0, 0, 255));
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("Current");

        jLabel71.setBackground(new java.awt.Color(204, 204, 204));
        jLabel71.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel71.setText("Address:");
        jLabel71.setOpaque(true);

        deleteMallBtn2.setBackground(new java.awt.Color(255, 0, 0));
        deleteMallBtn2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        deleteMallBtn2.setForeground(new java.awt.Color(255, 255, 255));
        deleteMallBtn2.setText("DELETE");
        deleteMallBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMallBtn2ActionPerformed(evt);
            }
        });

        modifyMallBtn2.setBackground(new java.awt.Color(0, 0, 255));
        modifyMallBtn2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        modifyMallBtn2.setForeground(new java.awt.Color(255, 255, 255));
        modifyMallBtn2.setText("MODIFY");
        modifyMallBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyMallBtn2ActionPerformed(evt);
            }
        });

        deleteMallBtn1.setBackground(new java.awt.Color(255, 0, 0));
        deleteMallBtn1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        deleteMallBtn1.setForeground(new java.awt.Color(255, 255, 255));
        deleteMallBtn1.setText("DELETE");
        deleteMallBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMallBtn1ActionPerformed(evt);
            }
        });

        modifyMallBtn1.setBackground(new java.awt.Color(0, 0, 255));
        modifyMallBtn1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        modifyMallBtn1.setForeground(new java.awt.Color(255, 255, 255));
        modifyMallBtn1.setText("MODIFY");
        modifyMallBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyMallBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(currentMallName)
                                    .addComponent(newMallName, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(currentAddress))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel45)
                                    .addComponent(jLabel55)
                                    .addComponent(jLabel66)
                                    .addComponent(jLabel61)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mallCMB, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(48, 67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(deleteMallBtn2)
                        .addGap(18, 18, 18)
                        .addComponent(modifyMallBtn2)
                        .addGap(264, 264, 264))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(deleteMallBtn1)
                        .addGap(18, 18, 18)
                        .addComponent(modifyMallBtn1)
                        .addGap(267, 267, 267))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(mallCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteMallBtn1)
                    .addComponent(modifyMallBtn1))
                .addGap(34, 34, 34)
                .addComponent(jLabel44)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(currentMallName, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newMallName, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel55)))
                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(currentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel66))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel61)))
                    .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteMallBtn2)
                    .addComponent(modifyMallBtn2))
                .addGap(156, 156, 156))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1))
        );

        jTabbedPane1.addTab("Mall", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filterMallCMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterMallCMBActionPerformed
        Object selectedMall = filterMallCMB.getSelectedItem();
        if (selectedMall == null) {
            return;
        }

        String mallName = selectedMall.toString().trim();
        currentStoreTabMall = controller.getMall(mallName);
        newStoreTabMall = currentStoreTabMall;

        populateCurrentFloorCMBs();
        populateNewFloorCMBs();

        filterStoreCMB.removeAllItems();
        stores = controller.getListOfStores(mallName);
        for (Store store : stores) {
            filterStoreCMB.addItem(store.getName());
        }

    }//GEN-LAST:event_filterMallCMBActionPerformed

    private void filterStoreCMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterStoreCMBActionPerformed
        int currentStoreIndex = filterStoreCMB.getSelectedIndex();
        if (stores == null) {
            clearEditFields();
            return;
        }
        if (currentStoreIndex == -1) {
            clearEditFields();
            return;
        }
        currentStore = stores.get(currentStoreIndex);
        currentTab = 0;
        populateFields();
    }//GEN-LAST:event_filterStoreCMBActionPerformed

    private void newMallCMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMallCMBActionPerformed
        Object selectedNewMall = newMallCMB.getSelectedItem();
        if (selectedNewMall == null) {
            return;
        }
        String newMallName = selectedNewMall.toString();
        newStoreTabMall = controller.getMall(newMallName);

        currentTab = 0;

        populateNewFloorCMBs();

    }//GEN-LAST:event_newMallCMBActionPerformed

    private void ModifyBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyBtn1ActionPerformed
        //Prompt the user to confirm delete operation
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to modify? Store " + currentStore.getName() + " will be modified", "Delete Confirmation", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.NO_OPTION || option == JOptionPane.CLOSED_OPTION || option == JOptionPane.CLOSED_OPTION) {
            return;
        }
        currentTab = 0;

        controller.modifyStore(currentStore, this);
    }//GEN-LAST:event_ModifyBtn1ActionPerformed

    private void DeleteBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtn1ActionPerformed
        //Prompt the user to confirm delete operation
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete? Store " + currentStore.getName() + " will be deleted", "Delete Confirmation", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.NO_OPTION || option == JOptionPane.CLOSED_OPTION || option == JOptionPane.CLOSED_OPTION) {
            return;
        }
        currentTab = 0;

        controller.deleteStore(currentStore, this);
    }//GEN-LAST:event_DeleteBtn1ActionPerformed

    private void ModifyBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyBtn2ActionPerformed
        //Prompt the user to confirm delete operation
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to modify? Store " + currentStore.getName() + " will be modified", "Delete Confirmation", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.NO_OPTION || option == JOptionPane.CLOSED_OPTION || option == JOptionPane.CLOSED_OPTION) {
            return;
        }
        currentTab = 0;

        controller.modifyStore(currentStore, this);
    }//GEN-LAST:event_ModifyBtn2ActionPerformed

    private void DeleteBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtn2ActionPerformed
        //Prompt the user to confirm delete operation
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete? Store " + currentStore.getName() + " will be deleted", "Delete Confirmation", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.NO_OPTION || option == JOptionPane.CLOSED_OPTION || option == JOptionPane.CLOSED_OPTION) {
            return;
        }
        currentTab = 0;

        controller.deleteStore(currentStore, this);

    }//GEN-LAST:event_DeleteBtn2ActionPerformed

    private void modifyMallBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyMallBtn1ActionPerformed
        //Prompt the user to confirm delete operation
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to modify? Mall " + currentStore.getName() + " will be modified", "Delete Confirmation", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.NO_OPTION || option == JOptionPane.CLOSED_OPTION || option == JOptionPane.CLOSED_OPTION) {
            return;
        }
        currentTab = 1;

        controller.modifyMall(currentMallTabMall, this);

    }//GEN-LAST:event_modifyMallBtn1ActionPerformed

    private void deleteMallBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMallBtn1ActionPerformed
        //Prompt the user to confirm delete operation
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete? Store " + currentStore.getName() + " will be deleted", "Delete Confirmation", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.NO_OPTION || option == JOptionPane.CLOSED_OPTION || option == JOptionPane.CLOSED_OPTION) {
            return;
        }
        currentTab = 1;

        controller.deleteMall(currentMallTabMall, this);

    }//GEN-LAST:event_deleteMallBtn1ActionPerformed

    private void modifyMallBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyMallBtn2ActionPerformed
        //Prompt the user to confirm delete operation
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to modify? Store " + currentStore.getName() + " will be modified", "Delete Confirmation", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.NO_OPTION || option == JOptionPane.CLOSED_OPTION || option == JOptionPane.CLOSED_OPTION) {
            return;
        }
        currentTab = 1;

        controller.modifyMall(currentMallTabMall, this);

    }//GEN-LAST:event_modifyMallBtn2ActionPerformed

    private void deleteMallBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMallBtn2ActionPerformed
        //Prompt the user to confirm delete operation
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete? Store " + currentStore.getName() + " will be deleted", "Delete Confirmation", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.NO_OPTION || option == JOptionPane.CLOSED_OPTION || option == JOptionPane.CLOSED_OPTION) {
            return;
        }
        currentTab = 1;
        controller.deleteMall(currentMallTabMall, this);

    }//GEN-LAST:event_deleteMallBtn2ActionPerformed

    private void mallCMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mallCMBActionPerformed
        Object selectedMall = mallCMB.getSelectedItem();
        if (selectedMall == null) {
            return;
        }

        String mallName = selectedMall.toString().trim();
        currentMallTabMall = controller.getMall(mallName);
        currentTab = 1;

        populateFields();

    }//GEN-LAST:event_mallCMBActionPerformed

    @Override
    public AttributeCollection getAttributes() {
        AttributeCollection attributes = new AttributeCollection();
        if (currentTab == 0) {
            String floor = floors[Integer.parseInt(newFloorCMB.getSelectedItem().toString())];
            attributes.add(new Attribute(Name.PURPOSE, newPurposeCMB.getSelectedItem().toString(), Table.PROPERTIES));
            String storeClass = newClassCMB.getSelectedItem().toString();
            attributes.add(new Attribute(Name.CLASS, newClassCMB.getSelectedItem().toString(), Table.PROPERTIES));
            attributes.add(new Attribute(Name.NAME, newStoreName.getText(), Table.PROPERTIES));
            attributes.add(new Attribute(Name.SPACE, newSpace.getText(), Table.PROPERTIES));
            attributes.add(new Attribute(Name.ANNUAL_RATE, newAnnual.getText(), Table.PROPERTIES));
            attributes.add(new Attribute(Name.BI_ANNUAL_RATE, newBiAnnual.getText(), Table.PROPERTIES));
            attributes.add(new Attribute(Name.QUARTERLY_RATE, newQuarterly.getText(), Table.PROPERTIES));
            attributes.add(new Attribute(Name.MONTHLY_RATE, newMonthly.getText(), Table.PROPERTIES));

            attributes.add(new Attribute(Name.STORE_NUM, floor + newStoreNumber.getText(), Table.LOCS));
            attributes.add(new Attribute(Name.MALL_NUM, String.valueOf(newStoreTabMall.getMallNum()), Table.LOCS));
        } else {
            attributes.add(new Attribute(Name.NAME, newMallName.getText(), Table.MALLS));
            attributes.add(new Attribute(Name.ADDRESS, newAddress.getText(), Table.MALLS));

        }
        return attributes;
    }

    @Override
    public Filters getFilters() {
        Filters filters = new Filters();

        String floor = floors[(int) newFloorCMB.getSelectedItem()];
        filters.addEqual(new Attribute(Name.NAME, filterMallCMB.getSelectedItem().toString(), Table.MALLS));
        filters.addEqual(new Attribute(Name.STORE_NUM, floor + filterStoreCMB.getSelectedItem().toString(), Table.LOCS));
        return filters;
    }

    @Override
    public void populateFields() {
        if (currentTab == 0) {
            populateStoreTabFields();
        } else {
            populateMallTabFields();
        }

    }

    @Override
    public void resetFields() {
        filterMallCMB.removeAllItems();
        filterFloorCMB.removeAllItems();
        filterStoreCMB.removeAllItems();
        clearEditFields();

        populateFilterMallCMBs();
    }

    private void clearEditFields() {
        currentMallCMB.removeAllItems();
        newMallCMB.removeAllItems();
        currentFloorCMB.removeAllItems();
        newFloorCMB.removeAllItems();
        currentPurposeCMB.removeAllItems();
        newPurposeCMB.removeAllItems();
        currentClassCMB.removeAllItems();
        newClassCMB.removeAllItems();

        currentStoreName.setText("");
        newStoreName.setText("");
        currentStoreNumber.setText("");
        newStoreNumber.setText("");
        currentSpace.setText("");
        newSpace.setText("");
        currentAnnual.setText("");
        newAnnual.setText("");
        currentBiAnnual.setText("");
        newBiAnnual.setText("");
        currentQuarterly.setText("");
        newQuarterly.setText("");
        currentMonthly.setText("");
        newMonthly.setText("");
    }

    private void populateStoreTabFields() {
        clearEditFields();
        populateEditMallCMBs();
        newStoreTabMall = currentStoreTabMall;
        currentMallCMB.setSelectedItem(currentStoreTabMall.getName());
        newMallCMB.setSelectedItem(newStoreTabMall.getName());

        populateCurrentFloorCMBs();
        populateNewFloorCMBs();
        currentFloorCMB.setSelectedItem(currentStore.getFloor());
        newFloorCMB.setSelectedItem(currentStore.getFloor());

        populateGenericCMBs();
        currentPurposeCMB.setSelectedItem(currentStore.getPurpose());
        newPurposeCMB.setSelectedItem(currentStore.getPurpose());
        currentClassCMB.setSelectedItem(currentStore.getStoreClass());
        newClassCMB.setSelectedItem(currentStore.getStoreClass());

        currentStoreName.setText(currentStore.getName());
        newStoreName.setText(currentStore.getName());

        currentStoreNumber.setText(String.valueOf(currentStore.getStoreNumber()));
        newStoreNumber.setText(String.valueOf(currentStore.getStoreNumber()));

        currentSpace.setText(String.valueOf(currentStore.getSpace()));
        newSpace.setText(String.valueOf(currentStore.getSpace()));

        currentAnnual.setText(String.valueOf(currentStore.getAnnualRate()));
        newAnnual.setText(String.valueOf(currentStore.getAnnualRate()));

        currentBiAnnual.setText(String.valueOf(currentStore.getBiAnnualRate()));
        newBiAnnual.setText(String.valueOf(currentStore.getBiAnnualRate()));

        currentQuarterly.setText(String.valueOf(currentStore.getQuarterlyRate()));
        newQuarterly.setText(String.valueOf(currentStore.getQuarterlyRate()));

        currentMonthly.setText(String.valueOf(currentStore.getMonthlyRate()));
        newMonthly.setText(String.valueOf(currentStore.getMonthlyRate()));

    }

    private void populateMallTabFields() {
        currentMallName.setText(currentMallTabMall.getName());
        newMallName.setText(currentMallTabMall.getName());

        currentAddress.setText(currentMallTabMall.getAddress());
        newAddress.setText(currentMallTabMall.getAddress());

    }

    private void populateEditMallCMBs() {
        ArrayList<Mall> malls;

        currentMallCMB.removeAllItems();
        newMallCMB.removeAllItems();

        malls = controller.getListOfMalls();
        for (Mall mall : malls) {
            currentMallCMB.addItem(mall.getName());
            newMallCMB.addItem(mall.getName());

        }

    }

    private void populateFilterMallCMBs() {
        ArrayList<Mall> malls;

        filterMallCMB.removeAllItems();
        mallCMB.removeAllItems();

        malls = controller.getListOfMalls();
        for (Mall mall : malls) {
            filterMallCMB.addItem(mall.getName());
            mallCMB.addItem(mall.getName());
        }
    }

    private void populateCurrentFloorCMBs() {
        int floors = currentStoreTabMall.getNumFloors();

        filterFloorCMB.removeAllItems();
        currentFloorCMB.removeAllItems();

        for (int i = 0; i < floors; i++) {
            filterFloorCMB.addItem(String.valueOf(i));
            currentFloorCMB.addItem(String.valueOf(i));
        }
    }

    private void populateNewFloorCMBs() {
        int floors = newStoreTabMall.getNumFloors();

        newFloorCMB.removeAllItems();

        for (int i = 0; i < floors; i++) {
            newFloorCMB.addItem(String.valueOf(i));
        }
    }

    private void populateGenericCMBs() {
        currentPurposeCMB.removeAllItems();
        newPurposeCMB.removeAllItems();

        currentClassCMB.removeAllItems();
        newClassCMB.removeAllItems();

        ArrayList<String> values;

        values = controller.getClasses();
        for (String classValue : values) {
            currentClassCMB.addItem(classValue);
            newClassCMB.addItem(classValue);

        }

        values = controller.getPurposes();
        for (String purpose : values) {
            currentPurposeCMB.addItem(purpose);
            newPurposeCMB.addItem(purpose);

        }

    }

    private void hideCurrentFields() {
        currentMallCMB.setEnabled(false);
        currentFloorCMB.setEnabled(false);
        currentPurposeCMB.setEnabled(false);
        currentClassCMB.setEnabled(false);
        currentStoreName.setEnabled(false);
        currentStoreNumber.setEnabled(false);
        currentSpace.setEnabled(false);
        currentAnnual.setEnabled(false);
        currentBiAnnual.setEnabled(false);
        currentQuarterly.setEnabled(false);
        currentMonthly.setEnabled(false);
        currentMallName.setEnabled(false);
        currentAddress.setEnabled(false);

        currentMallCMB.setForeground(Color.PINK);
        currentFloorCMB.setForeground(Color.PINK);
        currentPurposeCMB.setForeground(Color.PINK);
        currentClassCMB.setForeground(Color.PINK);
        currentStoreName.setForeground(Color.PINK);
        currentStoreNumber.setForeground(Color.PINK);
        currentSpace.setForeground(Color.PINK);
        currentAnnual.setForeground(Color.PINK);
        currentBiAnnual.setForeground(Color.PINK);
        currentQuarterly.setForeground(Color.PINK);
        currentMonthly.setForeground(Color.PINK);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteBtn1;
    private javax.swing.JButton DeleteBtn2;
    private javax.swing.JButton ModifyBtn1;
    private javax.swing.JButton ModifyBtn2;
    private javax.swing.JTextField currentAddress;
    private javax.swing.JTextField currentAnnual;
    private javax.swing.JTextField currentBiAnnual;
    private javax.swing.JComboBox<String> currentClassCMB;
    private javax.swing.JComboBox<String> currentFloorCMB;
    private javax.swing.JComboBox<String> currentMallCMB;
    private javax.swing.JTextField currentMallName;
    private javax.swing.JTextField currentMonthly;
    private javax.swing.JComboBox<String> currentPurposeCMB;
    private javax.swing.JTextField currentQuarterly;
    private javax.swing.JTextField currentSpace;
    private javax.swing.JTextField currentStoreName;
    private javax.swing.JTextField currentStoreNumber;
    private javax.swing.JButton deleteMallBtn1;
    private javax.swing.JButton deleteMallBtn2;
    private javax.swing.JComboBox<String> filterFloorCMB;
    private javax.swing.JComboBox<String> filterMallCMB;
    private javax.swing.JComboBox<String> filterStoreCMB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> mallCMB;
    private javax.swing.JButton modifyMallBtn1;
    private javax.swing.JButton modifyMallBtn2;
    private javax.swing.JTextField newAddress;
    private javax.swing.JTextField newAnnual;
    private javax.swing.JTextField newBiAnnual;
    private javax.swing.JComboBox<String> newClassCMB;
    private javax.swing.JComboBox<String> newFloorCMB;
    private javax.swing.JComboBox<String> newMallCMB;
    private javax.swing.JTextField newMallName;
    private javax.swing.JTextField newMonthly;
    private javax.swing.JComboBox<String> newPurposeCMB;
    private javax.swing.JTextField newQuarterly;
    private javax.swing.JTextField newSpace;
    private javax.swing.JTextField newStoreName;
    private javax.swing.JTextField newStoreNumber;
    // End of variables declaration//GEN-END:variables
}
