CREATE TABLE UTILITY_CONSUMPTION(
    UTILITY_ID CHAR(10, 0) CONSTRAINT UTILITY_CONSUMPTION_UTILITY_ID_PK PRIMARY KEY CONSTRAINT UTILITY_CONSUMPTION_UTILITYID_FORM CHECK(UTILITY_ID LIKE 'U%'),
    ELECONSUMP FLOAT CONSTRAINT UTILITY_CONSUMPTION_ELECONSUMP_NONNEGATIVE CHECK (ELECONSUMP>=0),
    ELECHARGE DECIMAL (10, 2) CONSTRAINT UTILITY_CONSUMPTION_ELECHARGE_NONNEGATIVE CHECK (ELECHARGE>=0),
    WATCONSUMP FLOAT CONSTRAINT UTILITY_CONSUMPTION_WATCONSUMP_NONNEGATIVE CHECK (WATCONSUMP>=0),
    WATCHARGE DECIMAL (10, 2) CONSTRAINT UTILITY_CONSUMPTION_WATCHARGE_NONNEGATIVE CHECK (WATCHARGE>=0),
    WASTEDISPOSED FLOAT CONSTRAINT UTILITY_CONSUMPTION_WASTEDISPOSED_NONNEGATIVE CHECK (WASTEDISPOSED>=0),
    WASTECHARGE DECIMAL (10, 2) CONSTRAINT UTILITY_CONSUMPTION_WASTECHARGE_NONNEGATIVE CHECK (WASTECHARGE>=0)
);

CREATE TABLE MAINTENANCE_REQUEST(
    BILL_NUM CHAR(10, 0),
    REQUEST_NUM CHAR(10, 0) CONSTRAINT MAINTENANCE_REQUEST_REQUEST_NUM_PK PRIMARY KEY,
    LEASEID CHAR (10, 0),
    DESCRIPTION VARCHAR(1000),
    STATUS VARCHAR(200),
    CHARGE DECIMAL (10, 2) CHECK (CHARGE >= 0),
    ASSIGNED_TECH VARCHAR(20)
);

--BillNum foreign key
--LeaseID foreign key
--ASSIGNED_TECH foreign key

CRETAE TABLE BILL(
BILL_NUM,
DUE_date,
Total_AMOUNT,
UTILITY_ID,
MAINTENANCE_ID

);